# Generated by Django 6.0.2 on 2026-02-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogtagindexpag'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogTagIndexPag',
            new_name='BlogTagIndexPage',
        ),
    ]
