# Generated by Django 6.0.2 on 2026-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='Linkedin URL')),
                ('github_url', models.URLField(blank=True, verbose_name='Github URL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
